name: flutter_parking_management

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  flutter_modular: ^5.0.3
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_svg: ^1.1.6
  dio: ^4.0.6
  lottie: ^2.2.0
  intl: ^0.17.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  flutter_lints: ^2.0.0
  dart_code_metrics: ^4.17.0
  hive_generator: ^1.1.1
  mocktail: ^0.3.0
  flutter_native_splash: ^2.1.1
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
