name: flutter_parking_management

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  flutter_modular: ^6.0.4+1
  google_fonts: ^4.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.7
  lottie: ^2.2.0
  intl: ^0.18.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.6.0
  hive_generator: ^2.0.1
  mocktail: ^1.0.0
  flutter_native_splash: ^2.1.1
  flutter_launcher_icons: ^0.13.1
  bloc_test: ^9.1.0
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/vectors/
    - assets/images/
    - assets/jsons/
